name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main # O deploy acontecerá automaticamente sempre que você fizer push na main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build -x test

      - name: Generate deployment package
        run: |
          rm -f build/libs/*-plain.jar
          zip -j deploy.zip build/libs/*.jar

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: PhoneLoginApp
          environment_name: PhoneLoginApp-env
          version_label: v-${{ github.run_number }}
          region: us-east-2
          deployment_package: deploy.zip
